/**
 * Markdown report formatter with before/after code examples.
 */

/**
 * @param {import("../scanner.js").ScanResult[]} results
 * @param {number} totalDeps
 * @param {string[]} packageJsons
 * @returns {string}
 */
export function formatMarkdown(results, totalDeps, packageJsons) {
  const lines = [];

  lines.push("# Browser-Native Dependency Report");
  lines.push("");
  lines.push(
    `Scanned **${packageJsons.length}** package.json file(s), **${totalDeps}** total dependencies.`
  );
  lines.push("");

  if (results.length === 0) {
    lines.push(
      "✅ **No replaceable dependencies found.** Your project is already using native APIs."
    );
    return lines.join("\n");
  }

  const full = results.filter((r) => r.replacement.confidence === "full").length;
  const partial = results.length - full;
  lines.push(
    `Found **${results.length}** replaceable dependencies (**${full}** full, **${partial}** partial).`
  );
  lines.push("");

  // Group by category
  /** @type {Map<string, typeof results>} */
  const byCategory = new Map();
  for (const r of results) {
    const cat = r.replacement.category;
    if (!byCategory.has(cat)) byCategory.set(cat, []);
    byCategory.get(cat).push(r);
  }

  for (const [category, items] of byCategory) {
    lines.push(`## ${category}`);
    lines.push("");

    for (const r of items) {
      const badge =
        r.replacement.confidence === "full" ? "✅ Full replacement" : "⚠️ Partial replacement";
      const depType = r.type === "devDep" ? " *(devDependency)*" : "";

      lines.push(`### \`${r.name}\`${depType}`);
      lines.push("");
      lines.push(`**${badge}** → **${r.replacement.browserApi}**`);
      lines.push("");

      if (r.replacement.notes) {
        lines.push(`> ${r.replacement.notes}`);
        lines.push("");
      }

      // Browser support table
      const mb = r.replacement.minBrowser;
      lines.push("| Chrome | Firefox | Safari | Edge | Node.js |");
      lines.push("|--------|---------|--------|------|---------|");
      lines.push(
        `| ${fmtVer(mb.chrome)} | ${fmtVer(mb.firefox)} | ${fmtVer(mb.safari)} | ${fmtVer(mb.edge)} | ${fmtVer(mb.node)} |`
      );
      lines.push("");

      lines.push("**Before** (with package):");
      lines.push("");
      lines.push("```javascript");
      lines.push(r.replacement.before);
      lines.push("```");
      lines.push("");

      lines.push("**After** (native API):");
      lines.push("");
      lines.push("```javascript");
      lines.push(r.replacement.after);
      lines.push("```");
      lines.push("");
      lines.push("---");
      lines.push("");
    }
  }

  lines.push(
    "*Generated by [browser-native](https://github.com/soderlind/browser-native)*"
  );

  return lines.join("\n");
}

/**
 * Format a version number for the support table.
 * @param {number} ver
 * @returns {string}
 */
function fmtVer(ver) {
  if (ver === Infinity) return "N/A";
  return String(ver) + "+";
}
